# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [ ]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
t = list(itertools.permutations('123', 3))

while True:
    try:
        dim = int(input('Введіть розмірність матриці: '))
        if dim > 0:
            matrix = random_matrix(dim)
            print(matrix)
            break
        else:
            print('Введіть ціле додатне число.')
    except ValueError:
        print('Введіть ціле додатне число.')

def perm_list(dim):
    '''
    
    '''
    dim_str = ''
    for i in range(1, dim + 1):
        dim_str += str(i)
    perm_list = list(itertools.permutations(dim_str, dim))
    return perm_list


[[6 3 3 9 8 1]
 [5 3 9 0 6 8]
 [0 9 5 8 2 2]
 [6 2 6 7 8 2]
 [7 0 1 6 2 2]
 [3 2 2 6 9 6]]
[('1', '2', '3', '4', '5', '6'), ('1', '2', '3', '4', '6', '5'), ('1', '2', '3', '5', '4', '6'), ('1', '2', '3', '5', '6', '4'), ('1', '2', '3', '6', '4', '5'), ('1', '2', '3', '6', '5', '4'), ('1', '2', '4', '3', '5', '6'), ('1', '2', '4', '3', '6', '5'), ('1', '2', '4', '5', '3', '6'), ('1', '2', '4', '5', '6', '3'), ('1', '2', '4', '6', '3', '5'), ('1', '2', '4', '6', '5', '3'), ('1', '2', '5', '3', '4', '6'), ('1', '2', '5', '3', '6', '4'), ('1', '2', '5', '4', '3', '6'), ('1', '2', '5', '4', '6', '3'), ('1', '2', '5', '6', '3', '4'), ('1', '2', '5', '6', '4', '3'), ('1', '2', '6', '3', '4', '5'), ('1', '2', '6', '3', '5', '4'), ('1', '2', '6', '4', '3', '5'), ('1', '2', '6', '4', '5', '3'), ('1', '2', '6', '5', '3', '4'), ('1', '2', '6', '5', '4', '3'), ('1', '3', '2', '4', '5', '6'), ('1', '3', '2', '4', '6', '5'), ('1', '3', '2', '5', '4', '6'), ('1', '3', '2', '5', '6', '4'), ('1', '3', '