# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [6]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
t = list(itertools.permutations('123', 3))

while True:
    try:
        dim = int(input('Enter the dimension of the matrix: '))
        if dim > 0:
            matrix = random_matrix(dim)
            print(matrix)
            break
        else:
            print('Enter a positive integer.')
    except ValueError:
        print('Enter a positive integer.')

def perm_list(dim):
    '''
    The function creates a list of permutations of values from 0 to a value 1 less than the dimension of the given matrix.
    '''
    perm_list = list(itertools.permutations(range(dim), dim))
    return perm_list

def element_product(perms, dim, matrix):
    '''
    The function calculates products of elements and determines their signs.
    '''
    for j_indices in perms:
        perms.insert(perms.index(j_indices), list(j_indices))
        perms.remove(j_indices)
        
    i_indices = []
    for i in range(dim):
        i_indices.append(i)
        
    det_additions = []
    det_addition = 1
    for j_indices in perms:
        for i, j in zip(i_indices, j_indices):
            det_addition = det_addition * matrix[i][j]
        det_additions.append(int(det_addition))
        det_addition = 1
        
    sign_list = []
    inverse_number = 0
    for j_indices in perms:
        j_indices_sorted = j_indices[:]
        j_indices_sorted.sort()
        while True:
            for i in range(len(j_indices) - 1):
                if j_indices[i] > j_indices[i + 1]:
                    j_indices[i], j_indices[i + 1] = j_indices[i + 1], j_indices[i]
                    inverse_number += 1
            if j_indices == j_indices_sorted:
                break
        if inverse_number % 2 == 0:
            sign_list.append(1)
        else:
            sign_list.append(-1)
        inverse_number = 0

    signed_det_additions = []
    for a, b in zip(sign_list, det_additions):
        signed_det_additions.append(a * b)
        
    return signed_det_additions

def sum(signed_det_additions):
    '''
    The function adds products to calculate the value of the determinant.
    '''
    determinant = 0
    for det_addition in signed_det_additions:
        determinant += det_addition
    return determinant

print(sum(element_product(perm_list(dim), dim, matrix)))
print(np.linalg.det(matrix))

[[2 5 4 0 3 2 0 4]
 [2 0 1 6 0 3 7 5]
 [6 6 8 4 3 4 3 2]
 [1 4 3 9 8 8 5 5]
 [4 0 0 4 9 2 5 3]
 [0 8 9 0 3 8 0 6]
 [9 2 3 7 4 1 7 2]
 [2 4 4 9 7 8 1 9]]
425840
425839.99999999936
